import { ed25519 } from '@noble/curves/ed25519';
import { sha256 } from '@noble/hashes/sha256';
import bs58 from 'bs58';
export const PROGRAM_ID = '2Z7xH99Z4YvG4U2Ew5PUZtVh8FE1VRhQ1Mo9dFvRvS3Q';
export const SYSTEM = '11111111111111111111111111111111';
export const TOKEN = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA';
export const INSTRUCTIONS = 'Sysvar1nstructions1111111111111111111111111';
export const RENT = 'SysvarRent111111111111111111111111111111111';
export const USDC = 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v';
export const JUPITER_V6 = 'JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4';
export type Key = { publicKey: string; secret: Uint8Array };
export type Meta = { address: string; signer?: boolean; writable?: boolean };
export type Instruction = { program: string; accounts: Meta[]; data: Uint8Array };
export const concat = (...arrays: Uint8Array[]) => Uint8Array.from(arrays.flatMap(a => [...a]));
export const utf8 = (s: string) => new TextEncoder().encode(s);
export function address(s: string): Uint8Array { const a = bs58.decode(s); if (a.length !== 32) throw Error('INVALID_ADDRESS'); return a; }
export function u64(value: bigint): Uint8Array { if (value < 0n || value > 18446744073709551615n) throw Error('INVALID_U64'); const a = new Uint8Array(8); new DataView(a.buffer).setBigUint64(0,value,true); return a; }
export function i64(value: bigint): Uint8Array { if(value < -(2n**63n) || value > 2n**63n-1n)throw Error('INVALID_I64');const a = new Uint8Array(8);new DataView(a.buffer).setBigInt64(0,value,true);return a; }
export function u32(value: number): Uint8Array {if(!Number.isInteger(value) || value<0 || value>0xffffffff)throw Error('INVALID_U32');const a=new Uint8Array(4);new DataView(a.buffer).setUint32(0,value,true);return a;}
export function keyFromSecret(secret: Uint8Array): Key { if(secret.length!==32 && secret.length!==64)throw Error('INVALID_SECRET');const seed=secret.slice(0,32);const publicKey=bs58.encode(ed25519.getPublicKey(seed));if(secret.length===64 && publicKey!==bs58.encode(secret.slice(32)))throw Error('KEY_MISMATCH');return {publicKey,secret:seed}; }
export function generateKey(): Key { return keyFromSecret(ed25519.utils.randomPrivateKey()); }
export function exportKey(key: Key): number[] {return [...key.secret,...address(key.publicKey)];}
export function pda(seeds: Uint8Array[], program=PROGRAM_ID): [string,number] {
 if(seeds.length>15 || seeds.some(s=>s.length>32))throw Error('INVALID_SEEDS');
 for(let bump=255;bump>=0;bump--){const hash=sha256(concat(...seeds,Uint8Array.of(bump),address(program),utf8('ProgramDerivedAddress')));let onCurve=true;try{ed25519.ExtendedPoint.fromHex(hash);}catch{onCurve=false;}if(!onCurve)return [bs58.encode(hash),bump];}throw Error('PDA_NOT_FOUND');
}
export const policyAddress = (owner:string,agent:string,program=PROGRAM_ID) => pda([utf8('policy'),address(owner),address(agent)],program)[0];
export const livePolicyAddress = (owner:string,agent:string,program=PROGRAM_ID) => pda([utf8('live-policy'),address(owner),address(agent)],program)[0];
export const poolAddress = (admin:string,mint:string,program=PROGRAM_ID) => pda([utf8('pool'),address(admin),address(mint)],program)[0];
export const discriminator = (name:string) => sha256(utf8('global:'+name)).slice(0,8);
export const meta = (a:string,signer=false,writable=false):Meta=>({address:a,signer,writable});
const short = (n:number):Uint8Array=>{const out=[];do{let b=n&127;n>>>=7;if(n)b|=128;out.push(b);}while(n);return Uint8Array.from(out);};
export function compile(payer:string,blockhash:string,instructions:Instruction[]):{message:Uint8Array;signers:string[]} {
 const entries=new Map<string,Meta>();entries.set(payer,meta(payer,true,true));
 for(const ix of instructions){for(const a of [...ix.accounts,meta(ix.program)]){const old=entries.get(a.address);entries.set(a.address,{...a,signer:!!(old?.signer||a.signer),writable:!!(old?.writable||a.writable)});}}
 const keys=[...entries.values()].sort((a,b)=>a.address===payer?-1:b.address===payer?1:Number(!!b.signer)*2+Number(!!b.writable)-Number(!!a.signer)*2-Number(!!a.writable));
 if(keys.length>256)throw Error('TOO_MANY_ACCOUNTS');
 const signers=keys.filter(k=>k.signer).map(k=>k.address), index=(a:string)=>keys.findIndex(k=>k.address===a);
 const header=Uint8Array.of(signers.length,keys.filter(k=>k.signer&&!k.writable).length,keys.filter(k=>!k.signer&&!k.writable).length);
 const wire=instructions.map(ix=>concat(Uint8Array.of(index(ix.program)),short(ix.accounts.length),Uint8Array.from(ix.accounts.map(a=>index(a.address))),short(ix.data.length),ix.data));
 return {message:concat(header,short(keys.length),...keys.map(k=>address(k.address)),address(blockhash),short(wire.length),...wire),signers};
}
export function signTransaction(compiled:ReturnType<typeof compile>, keys:Key[]):{bytes:Uint8Array;signature:string} {
 const signatures=compiled.signers.map(a=>{const key=keys.find(k=>k.publicKey===a);if(!key)throw Error('MISSING_SIGNER: '+a);return ed25519.sign(compiled.message,key.secret);});
 const bytes=concat(short(signatures.length),...signatures,compiled.message);if(bytes.length>1232)throw Error('TRANSACTION_TOO_LARGE');return {bytes,signature:bs58.encode(signatures[0])};
}
export class Rpc {
 constructor(public endpoint:string) { const u=new URL(endpoint);if(!['https:','http:'].includes(u.protocol))throw Error('INVALID_RPC'); }
 async call<T=any>(method:string,params:unknown[]=[]):Promise<T>{const res=await fetch(this.endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params}),signal:AbortSignal.timeout(20000)});if(!res.ok)throw Error('RPC_HTTP_'+res.status);const json=await res.json();if(json.error)throw Error(JSON.stringify(json.error));return json.result as T;}
 async assertTestCluster(){const hash=await this.call<string>('getGenesisHash');if(hash==='5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d')throw Error('MAINNET_DISABLED');const host=new URL(this.endpoint).hostname;if(hash!=='4uhcVJyU9pJkvQyS88uRDiswHXSCkY3zQawwpjk2NsNY' && !['127.0.0.1','localhost','[::1]'].includes(host))throw Error('EXPECTED_SOLANA_TESTNET');return hash;}
 async assertMainnet(){const hash=await this.call<string>('getGenesisHash');if(hash!=='5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d')throw Error('EXPECTED_SOLANA_MAINNET');return hash;}
 async account(key:string){const value=(await this.call('getAccountInfo',[key,{encoding:'base64',commitment:'confirmed'}])).value;if(!value)return null;return {owner:value.owner,data:Uint8Array.from(Buffer.from(value.data[0],'base64')),lamports:value.lamports};}
 async transaction(payer:Key,keys:Key[],ix:Instruction[]){await this.assertTestCluster();const {blockhash,lastValidBlockHeight}=(await this.call('getLatestBlockhash',[{commitment:'confirmed'}])).value;return {...signTransaction(compile(payer.publicKey,blockhash,ix),[payer,...keys]),lastValidBlockHeight};}
 async mainnetTransaction(payer:Key,keys:Key[],ix:Instruction[]){await this.assertMainnet();const {blockhash,lastValidBlockHeight}=(await this.call('getLatestBlockhash',[{commitment:'confirmed'}])).value;return {...signTransaction(compile(payer.publicKey,blockhash,ix),[payer,...keys]),lastValidBlockHeight};}
 async simulate(bytes:Uint8Array){return this.call('simulateTransaction',[Buffer.from(bytes).toString('base64'),{encoding:'base64',sigVerify:true,commitment:'confirmed'}]);}
 async send(bytes:Uint8Array){await this.assertTestCluster();return this.call<string>('sendTransaction',[Buffer.from(bytes).toString('base64'),{encoding:'base64',skipPreflight:false,preflightCommitment:'confirmed'}]);}
 async sendMainnet(bytes:Uint8Array){await this.assertMainnet();return this.call<string>('sendTransaction',[Buffer.from(bytes).toString('base64'),{encoding:'base64',skipPreflight:false,preflightCommitment:'confirmed'}]);}
 async confirm(signature:string,timeout=60000){const until=Date.now()+timeout;while(Date.now()<until){const s=(await this.call('getSignatureStatuses',[[signature],{searchTransactionHistory:true}])).value[0];if(s?.err)throw Error('TRANSACTION_FAILED: '+JSON.stringify(s.err));if(s?.confirmationStatus==='finalized')return s;await new Promise(r=>setTimeout(r,1200));}throw Error('CONFIRMATION_UNKNOWN');}
}
export const MAX_RECIPIENTS=8,MAX_PROGRAMS=4;
export type Policy={version:2;owner:string;agent:string;executor:string;pool:string;maxAmount:bigint;totalLimit:bigint;spent:bigint;expiresAt:bigint;nonce:bigint;minRate:bigint;active:boolean;bump:number;allowedRecipients:string[];allowedPrograms:string[]};
export type LivePolicy={version:1;owner:string;agent:string;executor:string;quoteMint:string;maxAmount:bigint;totalLimit:bigint;spent:bigint;expiresAt:bigint;nonce:bigint;active:boolean;bump:number;allowedRecipients:string[];allowedPrograms:string[]};
function checkedAddresses(values:string[],max:number):string[]{if(!Array.isArray(values)||values.length>max||new Set(values).size!==values.length)throw Error('INVALID_POLICY_ALLOWLIST');values.forEach(address);return values;}
const addressVector=(values:string[],max:number)=>concat(u32(checkedAddresses(values,max).length),...values.map(address));
export function decodePolicy(data:Uint8Array):Policy{const expected=sha256(utf8('account:PolicyV2')).slice(0,8);if(data.length<195||!expected.every((v,i)=>v===data[i])||data[8]!==2)throw Error('INVALID_POLICY_ACCOUNT');let at=9;const need=(n:number)=>{if(at+n>data.length)throw Error('INVALID_POLICY_ACCOUNT');};const key=()=>{need(32);const k=bs58.encode(data.slice(at,at+32));at+=32;return k;};const num=(signed=false)=>{need(8);const v=new DataView(data.buffer,data.byteOffset+at,8);at+=8;return signed?v.getBigInt64(0,true):v.getBigUint64(0,true);};const owner=key(),agent=key(),executor=key(),pool=key(),maxAmount=num(),totalLimit=num(),spent=num(),expiresAt=num(true),nonce=num(),minRate=num();need(2);if(data[at]>1)throw Error('INVALID_POLICY_ACCOUNT');const active=data[at++]===1,bump=data[at++];const vector=(max:number)=>{need(4);const count=new DataView(data.buffer,data.byteOffset+at,4).getUint32(0,true);at+=4;if(count>max)throw Error('INVALID_POLICY_ACCOUNT');need(count*32);const values=Array.from({length:count},key);if(new Set(values).size!==count)throw Error('INVALID_POLICY_ACCOUNT');return values;};return{version:2,owner,agent,executor,pool,maxAmount,totalLimit,spent,expiresAt,nonce,minRate,active,bump,allowedRecipients:vector(MAX_RECIPIENTS),allowedPrograms:vector(MAX_PROGRAMS)};}
export function decodeLivePolicy(data:Uint8Array):LivePolicy{const expected=sha256(utf8('account:LivePolicy')).slice(0,8);if(data.length<187||!expected.every((value,index)=>value===data[index])||data[8]!==1)throw Error('INVALID_LIVE_POLICY_ACCOUNT');let at=9;const need=(length:number)=>{if(at+length>data.length)throw Error('INVALID_LIVE_POLICY_ACCOUNT');};const key=()=>{need(32);const value=bs58.encode(data.slice(at,at+32));at+=32;return value;};const num=(signed=false)=>{need(8);const view=new DataView(data.buffer,data.byteOffset+at,8);at+=8;return signed?view.getBigInt64(0,true):view.getBigUint64(0,true);};const owner=key(),agent=key(),executor=key(),quoteMint=key(),maxAmount=num(),totalLimit=num(),spent=num(),expiresAt=num(true),nonce=num();need(2);if(data[at]>1)throw Error('INVALID_LIVE_POLICY_ACCOUNT');const active=data[at++]===1,bump=data[at++];const vector=(max:number)=>{need(4);const count=new DataView(data.buffer,data.byteOffset+at,4).getUint32(0,true);at+=4;if(count>max)throw Error('INVALID_LIVE_POLICY_ACCOUNT');need(count*32);const values=Array.from({length:count},key);if(new Set(values).size!==count)throw Error('INVALID_LIVE_POLICY_ACCOUNT');return values;};return{version:1,owner,agent,executor,quoteMint,maxAmount,totalLimit,spent,expiresAt,nonce,active,bump,allowedRecipients:vector(MAX_RECIPIENTS),allowedPrograms:vector(MAX_PROGRAMS)};}
export type Evaluation={decision:'ALLOW'|'DENY';reason:string;simulationSlot:number|null};
/** Evaluate signed bytes against current chain state. ALLOW is provisional; this never broadcasts. */
export async function evaluateTransaction(rpc:Rpc,bytes:Uint8Array):Promise<Evaluation>{try{await rpc.assertTestCluster();const simulation=await rpc.simulate(bytes);if(!simulation?.value||!('err'in simulation.value)||!Number.isSafeInteger(simulation.context?.slot))return{decision:'DENY',reason:'SIMULATION_UNAVAILABLE',simulationSlot:null};const denied=simulation.value.err!==null;return{decision:denied?'DENY':'ALLOW',reason:errorReason(simulation.value.logs,simulation.value.err),simulationSlot:simulation.context.slot};}catch(error){const message=error instanceof Error?error.message:'';return{decision:'DENY',reason:['MAINNET_DISABLED','EXPECTED_SOLANA_TESTNET'].includes(message)?message:'SIMULATION_UNAVAILABLE',simulationSlot:null};}}
export function createPoolIx(admin:string,quoteMint:string,outputMint:string,rate:bigint,program=PROGRAM_ID):Instruction{return {program,accounts:[meta(admin,true,true),meta(poolAddress(admin,outputMint,program),false,true),meta(SYSTEM)],data:concat(discriminator('create_pool'),address(quoteMint),address(outputMint),u64(rate))};}
export function createPolicyIx(p:{owner:string;agent:string;executor:string;allowedRecipients:string[];pool:string;maxAmount:bigint;totalLimit:bigint;expiresAt:bigint;minRate:bigint;allowedPrograms?:string[]},program=PROGRAM_ID):Instruction{return{program,accounts:[meta(p.owner,true,true),meta(policyAddress(p.owner,p.agent,program),false,true),meta(p.pool),meta(SYSTEM)],data:concat(discriminator('create_policy'),address(p.agent),address(p.executor),addressVector(p.allowedRecipients,MAX_RECIPIENTS),u64(p.maxAmount),u64(p.totalLimit),i64(p.expiresAt),addressVector(p.allowedPrograms??[TOKEN],MAX_PROGRAMS),u64(p.minRate))};}
export function createLivePolicyIx(p:{owner:string;agent:string;executor:string;quoteMint:string;allowedRecipients:string[];maxAmount:bigint;totalLimit:bigint;expiresAt:bigint;allowedPrograms:string[]},program=PROGRAM_ID):Instruction{return{program,accounts:[meta(p.owner,true,true),meta(livePolicyAddress(p.owner,p.agent,program),false,true),meta(p.quoteMint),meta(SYSTEM)],data:concat(discriminator('create_live_policy'),address(p.agent),address(p.executor),addressVector(p.allowedRecipients,MAX_RECIPIENTS),u64(p.maxAmount),u64(p.totalLimit),i64(p.expiresAt),addressVector(p.allowedPrograms,MAX_PROGRAMS))};}
export type SwapAccounts={agent:string;executor:string;policy:string;pool:string;vault:string;poolQuote:string;poolOutput:string;recipient:string};
export function swapIx(a:SwapAccounts,amount:bigint,minOutput:bigint,nonce:bigint,program=PROGRAM_ID):Instruction{return {program,accounts:[meta(a.agent,true),meta(a.executor,true),meta(a.policy,false,true),meta(a.pool),meta(a.vault,false,true),meta(a.poolQuote,false,true),meta(a.poolOutput,false,true),meta(a.recipient,false,true),meta(TOKEN),meta(INSTRUCTIONS)],data:concat(discriminator('execute_swap'),u64(amount),u64(minOutput),u64(nonce))};}
export function executeRouteIx(a:{agent:string;executor:string;policy:string;vault:string;destination:string},route:Instruction,amount:bigint,minOutput:bigint,nonce:bigint,program=PROGRAM_ID):Instruction{return{program,accounts:[meta(a.agent,true),meta(a.executor,true),meta(a.policy,false,true),meta(a.vault,false,true),meta(a.destination,false,true),meta(route.program),meta(TOKEN),meta(INSTRUCTIONS),...route.accounts],data:concat(discriminator('execute_route'),u64(amount),u64(minOutput),u64(nonce),u32(route.data.length),route.data)};}
export const revokeIx=(owner:string,policy:string,program=PROGRAM_ID):Instruction=>({program,accounts:[meta(owner,true),meta(policy,false,true)],data:discriminator('revoke')});
export const revokeLiveIx=(owner:string,policy:string,program=PROGRAM_ID):Instruction=>({program,accounts:[meta(owner,true),meta(policy,false,true)],data:discriminator('revoke_live')});
export function recoverIx(owner:string,policy:string,pool:string,vault:string,destination:string,amount:bigint,program=PROGRAM_ID):Instruction{return {program,accounts:[meta(owner,true),meta(policy),meta(pool),meta(vault,false,true),meta(destination,false,true),meta(TOKEN)],data:concat(discriminator('recover'),u64(amount))};}
export function recoverLiveIx(owner:string,policy:string,vault:string,destination:string,amount:bigint,program=PROGRAM_ID):Instruction{return{program,accounts:[meta(owner,true),meta(policy),meta(vault,false,true),meta(destination,false,true),meta(TOKEN)],data:concat(discriminator('recover_live'),u64(amount))};}
export const systemCreate=(payer:string,newAccount:string,lamports:bigint,space:bigint,owner:string):Instruction=>({program:SYSTEM,accounts:[meta(payer,true,true),meta(newAccount,true,true)],data:concat(u32(0),u64(lamports),u64(space),address(owner))});
export const initializeMint=(mint:string,authority:string,decimals=6):Instruction=>({program:TOKEN,accounts:[meta(mint,false,true),meta(RENT)],data:concat(Uint8Array.of(0,decimals),address(authority),Uint8Array.of(0))});
export const initializeToken=(account:string,mint:string,owner:string):Instruction=>({program:TOKEN,accounts:[meta(account,false,true),meta(mint),meta(owner),meta(RENT)],data:Uint8Array.of(1)});
export const mintTo=(mint:string,dest:string,authority:string,amount:bigint):Instruction=>({program:TOKEN,accounts:[meta(mint,false,true),meta(dest,false,true),meta(authority,true)],data:concat(Uint8Array.of(7),u64(amount))});
export function errorReason(logs:string[]|null,err:unknown):string{const known=logs?.map(l=>l.match(/Error Message: ([A-Z_]+)/)?.[1]).find(Boolean);return known || (err?'EXECUTION_REJECTED':'POLICY_SATISFIED');}
export function explorer(signature:string){return 'https://explorer.solana.com/tx/'+encodeURIComponent(signature)+'?cluster=testnet';}
