import test from 'node:test';import assert from 'node:assert/strict';
import {ed25519} from '@noble/curves/ed25519';
import {generateKey,address,compile,signTransaction,systemCreate,SYSTEM,policyAddress,pda,utf8,u64,decodePolicy,PROGRAM_ID} from '../packages/sdk/src/index.js';
import {parseIntent,pickCandidate,FIXTURES,previewPolicy} from '../packages/core/src/index.js';
test('signatures bind the full serialized message',()=>{const a=generateKey(),b=generateKey();const c=compile(a.publicKey,SYSTEM,[systemCreate(a.publicKey,b.publicKey,1n,0n,SYSTEM)]);const tx=signTransaction(c,[a,b]);assert.equal(tx.bytes[0],2);assert.ok(ed25519.verify(tx.bytes.slice(1,65),c.message,address(a.publicKey)));const altered=c.message.slice();altered[10]^=1;assert.equal(ed25519.verify(tx.bytes.slice(1,65),altered,address(a.publicKey)),false);assert.throws(()=>signTransaction(c,[a]),/MISSING_SIGNER/);});
test('PDA is deterministic and off curve',()=>{const a=generateKey(),b=generateKey();const p=policyAddress(a.publicKey,b.publicKey);assert.equal(p,policyAddress(a.publicKey,b.publicKey));assert.throws(()=>ed25519.ExtendedPoint.fromHex(address(p)));assert.notEqual(p,policyAddress(b.publicKey,a.publicKey));assert.throws(()=>pda([new Uint8Array(33)]));});
test('integer amounts cannot silently wrap',()=>{assert.throws(()=>u64(-1n));assert.throws(()=>u64(2n**64n));assert.equal(u64(100n)[0],100);assert.throws(()=>decodePolicy(new Uint8Array(250)));});
test('intent budget is exact and not a promised return',()=>{assert.equal(parseIntent('make me a million','100').budgetMicros,'100000000');assert.equal(parseIntent('buy','0.000001').budgetMicros,'1');assert.throws(()=>parseIntent('buy','-1'));assert.throws(()=>parseIntent('buy','1e3'));assert.equal(pickCandidate(FIXTURES).symbol,'BREAD');assert.throws(()=>pickCandidate([{...FIXTURES[0],source:'x'}]),/NO_VERIFIED/);});
test('preview boundaries fail closed',()=>{const p={active:true,expiresAt:100,maxAmount:'100',totalLimit:'150',spent:'60',recipient:'owner'};assert.equal(previewPolicy(p,{amount:'90',recipient:'owner'},99),'POLICY_SATISFIED');assert.equal(previewPolicy(p,{amount:'91',recipient:'owner'},99),'CUMULATIVE_LIMIT_EXCEEDED');assert.equal(previewPolicy({...p,active:false},{amount:'1',recipient:'owner'},99),'REVOKED');assert.equal(previewPolicy(p,{amount:'1',recipient:'attacker'},99),'RECIPIENT_NOT_ALLOWED');assert.equal(previewPolicy(p,{amount:'1',recipient:'owner'},100),'EXPIRED');});
